version: '2'
services:
    angularspringgulpapp-sonar:
        container_name: angularspringgulpapp-sonar
        image: sonarqube:6.1-alpine
        ports:
            - 9000:9000
            - 9092:9092
